// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO0vMoIAOO6ciqI6hgn08g4zurEE4UWw4',
    appId: '1:918506344102:android:0e407fa1c09e84e5f2ae67',
    messagingSenderId: '918506344102',
    projectId: 'revision2-33937',
    storageBucket: 'revision2-33937.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0XXJszN6gNzQ4tvBB8HpewRx5wYIX9dk',
    appId: '1:918506344102:ios:67a207e52c122c62f2ae67',
    messagingSenderId: '918506344102',
    projectId: 'revision2-33937',
    storageBucket: 'revision2-33937.appspot.com',
    androidClientId: '918506344102-ma14nnge3o55ac8g5gned16rjdb334qj.apps.googleusercontent.com',
    iosClientId: '918506344102-i3aqes2q5sc2jrjupp3hp3ikomd1cuj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication16',
  );
}
